### ISSUE TITLE
Pigallery2 not updating

### ISSUE THREAD

**Issue by rhatguy** [ItJustFox/unraidtemplate#3]
I see in the pigallery2 xml that its set to use the nightly debian buster image and I see on docker hub that that tag was updated last night, however I'm not seeing an update in my unraid instance and the installed instance still shows version 1.9.3 built in March '22.  Is there something that needs to change to cause unraid to pick up the new latest images from docker hub?

**Comment by rhatguy** [comment]
FYI, I manually specified to use the nightly by setting my container's repository to "bpatrik/pigallery2:nightly-debian-bullseye".  That seems to have worked.  I'm still not sure why its not doing that automatically based on the XML I see in this repository.

@ItJustFox ?

**Comment by ItJustFox** [comment]
Issue for that should be reported on the Unraid forum or discord, i'm not that on on Github, and for the repo, it's made like that, that when you install it on the CA unraid, you can choose latest or the 'beta' version

**Comment by ItJustFox** [comment]
Could you btw, please delete your Fork of the reposite ? 
Thanks aleadry

**Comment by rhatguy** [comment]
got it deleted.  Thx for building this.
