### ISSUE TITLE
unrelated question

### ISSUE THREAD

**Issue by Tyholmes09** [ItJustFox/unraidtemplate#4]
I'm sorry, this is the only way i could think to contact you.

i was wondering if you ever found a solution to this issue you had?

https://github.com/pterodactyl/panel/issues/3885

**Comment by ItJustFox** [comment]
> I'm sorry, this is the only way i could think to contact you.
> 
> i was wondering if you ever found a solution to this issue you had?
> 
> [pterodactyl/panel#3885](https://github.com/pterodactyl/panel/issues/3885)

Hello there the solution is to make an VM of Debian (or have an server with debian aside of unRAID(os) then put wings on it, and then Garry's mod, In fact some game like GMOD cannot be run docker in docker, like if Wings are aleadry on Docker some game on Steam won't work like gmod for dark reason, I didn't searched a lot why and how, but I guess it's from steam Download ect.
